---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
    exclude_paths:
      - spec/
  rubocop:
    enabled: true
    exclude_paths:
      -
ratings:
  paths:
    - Gemfile.lock
    - "**.rb"
    - "**.rake"
exclude_paths:
  - bin/
  - config/
  - public/
  - tmp/
  - db/
